---
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: gitpod
servers: 1
agents: 2
image: k3s
subnet: "172.18.0.0/16"
volumes:
  - volume: /usr/src:/usr/src
    nodeFilters:
      - agent:1
  - volume: /tmp/etc-hosts:/etc/hosts:shared
    nodeFilters:
      - agent:*
  - volume: /tmp/gitpod:/var/gitpod/workspaces:shared
    nodeFilters:
      - agent:1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    disableLoadbalancer: false
    disableRollback: true
  k3s:
    nodeLabels:
      - label: gitpod.io/workload_meta=true
        nodeFilters:
          - agent:0
      - label: gitpod.io/workload_ide=true
        nodeFilters:
          - agent:0
      - label: gitpod.io/workload_workspace_services=true
        nodeFilters:
          - agent:1
      - label: gitpod.io/workload_workspace_regular=true
        nodeFilters:
          - agent:1
      - label: gitpod.io/workload_workspace_headless=true
        nodeFilters:
          - agent:1
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime: {}
